/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as RatgeberWebsiteRelaunchKostenLeipzigRouteImport } from './routes/ratgeber/website-relaunch-kosten-leipzig'
import { Route as RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport } from './routes/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
import { Route as EnUeberMichRouteImport } from './routes/en/ueber-mich'
import { Route as EnReferenzenRouteImport } from './routes/en/referenzen'
import { Route as EnPreiseRouteImport } from './routes/en/preise'
import { Route as EnLeistungenRouteImport } from './routes/en/leistungen'
import { Route as EnKontaktRouteImport } from './routes/en/kontakt'
import { Route as EnImpressumRouteImport } from './routes/en/impressum'
import { Route as EnDatenschutzRouteImport } from './routes/en/datenschutz'
import { Route as EnAblaufRouteImport } from './routes/en/ablauf'
import { Route as ApiMetaCrmRouteImport } from './routes/api/meta-crm'
import { Route as EnRatgeberIndexRouteImport } from './routes/en/ratgeber/index'
import { Route as EnRatgeberWebsiteRelaunchKostenLeipzigRouteImport } from './routes/en/ratgeber/website-relaunch-kosten-leipzig'
import { Route as EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport } from './routes/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberWebsiteRelaunchKostenLeipzigRoute =
  RatgeberWebsiteRelaunchKostenLeipzigRouteImport.update({
    id: '/ratgeber/website-relaunch-kosten-leipzig',
    path: '/ratgeber/website-relaunch-kosten-leipzig',
    getParentRoute: () => rootRouteImport,
  } as any)
const RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute =
  RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport.update({
    id: '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen',
    path: '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnUeberMichRoute = EnUeberMichRouteImport.update({
  id: '/en/ueber-mich',
  path: '/en/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const EnReferenzenRoute = EnReferenzenRouteImport.update({
  id: '/en/referenzen',
  path: '/en/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPreiseRoute = EnPreiseRouteImport.update({
  id: '/en/preise',
  path: '/en/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeistungenRoute = EnLeistungenRouteImport.update({
  id: '/en/leistungen',
  path: '/en/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKontaktRoute = EnKontaktRouteImport.update({
  id: '/en/kontakt',
  path: '/en/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnImpressumRoute = EnImpressumRouteImport.update({
  id: '/en/impressum',
  path: '/en/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDatenschutzRoute = EnDatenschutzRouteImport.update({
  id: '/en/datenschutz',
  path: '/en/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAblaufRoute = EnAblaufRouteImport.update({
  id: '/en/ablauf',
  path: '/en/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCrmRoute = ApiMetaCrmRouteImport.update({
  id: '/api/meta-crm',
  path: '/api/meta-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRatgeberIndexRoute = EnRatgeberIndexRouteImport.update({
  id: '/en/ratgeber/',
  path: '/en/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRatgeberWebsiteRelaunchKostenLeipzigRoute =
  EnRatgeberWebsiteRelaunchKostenLeipzigRouteImport.update({
    id: '/en/ratgeber/website-relaunch-kosten-leipzig',
    path: '/en/ratgeber/website-relaunch-kosten-leipzig',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute =
  EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport.update({
    id: '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen',
    path: '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
  '/en/ablauf': typeof EnAblaufRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/preise': typeof EnPreiseRoute
  '/en/referenzen': typeof EnReferenzenRoute
  '/en/ueber-mich': typeof EnUeberMichRoute
  '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/ratgeber/website-relaunch-kosten-leipzig': typeof RatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en/': typeof EnIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/en/ratgeber/website-relaunch-kosten-leipzig': typeof EnRatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en/ratgeber/': typeof EnRatgeberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
  '/en/ablauf': typeof EnAblaufRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/preise': typeof EnPreiseRoute
  '/en/referenzen': typeof EnReferenzenRoute
  '/en/ueber-mich': typeof EnUeberMichRoute
  '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/ratgeber/website-relaunch-kosten-leipzig': typeof RatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en': typeof EnIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/en/ratgeber/website-relaunch-kosten-leipzig': typeof EnRatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en/ratgeber': typeof EnRatgeberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
  '/en/ablauf': typeof EnAblaufRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/preise': typeof EnPreiseRoute
  '/en/referenzen': typeof EnReferenzenRoute
  '/en/ueber-mich': typeof EnUeberMichRoute
  '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/ratgeber/website-relaunch-kosten-leipzig': typeof RatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en/': typeof EnIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': typeof EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  '/en/ratgeber/website-relaunch-kosten-leipzig': typeof EnRatgeberWebsiteRelaunchKostenLeipzigRoute
  '/en/ratgeber/': typeof EnRatgeberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
    | '/en/ablauf'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/preise'
    | '/en/referenzen'
    | '/en/ueber-mich'
    | '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/ratgeber/website-relaunch-kosten-leipzig'
    | '/en/'
    | '/ratgeber/'
    | '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/en/ratgeber/website-relaunch-kosten-leipzig'
    | '/en/ratgeber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
    | '/en/ablauf'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/preise'
    | '/en/referenzen'
    | '/en/ueber-mich'
    | '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/ratgeber/website-relaunch-kosten-leipzig'
    | '/en'
    | '/ratgeber'
    | '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/en/ratgeber/website-relaunch-kosten-leipzig'
    | '/en/ratgeber'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
    | '/en/ablauf'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/preise'
    | '/en/referenzen'
    | '/en/ueber-mich'
    | '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/ratgeber/website-relaunch-kosten-leipzig'
    | '/en/'
    | '/ratgeber/'
    | '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
    | '/en/ratgeber/website-relaunch-kosten-leipzig'
    | '/en/ratgeber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  PreiseRoute: typeof PreiseRoute
  ReferenzenRoute: typeof ReferenzenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberMichRoute: typeof UeberMichRoute
  ApiMetaCrmRoute: typeof ApiMetaCrmRoute
  EnAblaufRoute: typeof EnAblaufRoute
  EnDatenschutzRoute: typeof EnDatenschutzRoute
  EnImpressumRoute: typeof EnImpressumRoute
  EnKontaktRoute: typeof EnKontaktRoute
  EnLeistungenRoute: typeof EnLeistungenRoute
  EnPreiseRoute: typeof EnPreiseRoute
  EnReferenzenRoute: typeof EnReferenzenRoute
  EnUeberMichRoute: typeof EnUeberMichRoute
  RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute: typeof RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  RatgeberWebsiteRelaunchKostenLeipzigRoute: typeof RatgeberWebsiteRelaunchKostenLeipzigRoute
  EnIndexRoute: typeof EnIndexRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
  EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute: typeof EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute
  EnRatgeberWebsiteRelaunchKostenLeipzigRoute: typeof EnRatgeberWebsiteRelaunchKostenLeipzigRoute
  EnRatgeberIndexRoute: typeof EnRatgeberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/ratgeber'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/website-relaunch-kosten-leipzig': {
      id: '/ratgeber/website-relaunch-kosten-leipzig'
      path: '/ratgeber/website-relaunch-kosten-leipzig'
      fullPath: '/ratgeber/website-relaunch-kosten-leipzig'
      preLoaderRoute: typeof RatgeberWebsiteRelaunchKostenLeipzigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': {
      id: '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      path: '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      fullPath: '/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      preLoaderRoute: typeof RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ueber-mich': {
      id: '/en/ueber-mich'
      path: '/en/ueber-mich'
      fullPath: '/en/ueber-mich'
      preLoaderRoute: typeof EnUeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/referenzen': {
      id: '/en/referenzen'
      path: '/en/referenzen'
      fullPath: '/en/referenzen'
      preLoaderRoute: typeof EnReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/preise': {
      id: '/en/preise'
      path: '/en/preise'
      fullPath: '/en/preise'
      preLoaderRoute: typeof EnPreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leistungen': {
      id: '/en/leistungen'
      path: '/en/leistungen'
      fullPath: '/en/leistungen'
      preLoaderRoute: typeof EnLeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kontakt': {
      id: '/en/kontakt'
      path: '/en/kontakt'
      fullPath: '/en/kontakt'
      preLoaderRoute: typeof EnKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/impressum': {
      id: '/en/impressum'
      path: '/en/impressum'
      fullPath: '/en/impressum'
      preLoaderRoute: typeof EnImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/datenschutz': {
      id: '/en/datenschutz'
      path: '/en/datenschutz'
      fullPath: '/en/datenschutz'
      preLoaderRoute: typeof EnDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ablauf': {
      id: '/en/ablauf'
      path: '/en/ablauf'
      fullPath: '/en/ablauf'
      preLoaderRoute: typeof EnAblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-crm': {
      id: '/api/meta-crm'
      path: '/api/meta-crm'
      fullPath: '/api/meta-crm'
      preLoaderRoute: typeof ApiMetaCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ratgeber/': {
      id: '/en/ratgeber/'
      path: '/en/ratgeber'
      fullPath: '/en/ratgeber/'
      preLoaderRoute: typeof EnRatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ratgeber/website-relaunch-kosten-leipzig': {
      id: '/en/ratgeber/website-relaunch-kosten-leipzig'
      path: '/en/ratgeber/website-relaunch-kosten-leipzig'
      fullPath: '/en/ratgeber/website-relaunch-kosten-leipzig'
      preLoaderRoute: typeof EnRatgeberWebsiteRelaunchKostenLeipzigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen': {
      id: '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      path: '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      fullPath: '/en/ratgeber/was-kostet-eine-website-fuer-mein-unternehmen'
      preLoaderRoute: typeof EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  PreiseRoute: PreiseRoute,
  ReferenzenRoute: ReferenzenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberMichRoute: UeberMichRoute,
  ApiMetaCrmRoute: ApiMetaCrmRoute,
  EnAblaufRoute: EnAblaufRoute,
  EnDatenschutzRoute: EnDatenschutzRoute,
  EnImpressumRoute: EnImpressumRoute,
  EnKontaktRoute: EnKontaktRoute,
  EnLeistungenRoute: EnLeistungenRoute,
  EnPreiseRoute: EnPreiseRoute,
  EnReferenzenRoute: EnReferenzenRoute,
  EnUeberMichRoute: EnUeberMichRoute,
  RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute:
    RatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute,
  RatgeberWebsiteRelaunchKostenLeipzigRoute:
    RatgeberWebsiteRelaunchKostenLeipzigRoute,
  EnIndexRoute: EnIndexRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
  EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute:
    EnRatgeberWasKostetEineWebsiteFuerMeinUnternehmenRoute,
  EnRatgeberWebsiteRelaunchKostenLeipzigRoute:
    EnRatgeberWebsiteRelaunchKostenLeipzigRoute,
  EnRatgeberIndexRoute: EnRatgeberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
