/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AblaufRouteImport } from './routes/ablauf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMetaCrmRouteImport } from './routes/api/meta-crm'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AblaufRoute = AblaufRouteImport.update({
  id: '/ablauf',
  path: '/ablauf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaCrmRoute = ApiMetaCrmRouteImport.update({
  id: '/api/meta-crm',
  path: '/api/meta-crm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablauf': typeof AblaufRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/preise': typeof PreiseRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/api/meta-crm': typeof ApiMetaCrmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
  id:
    | '__root__'
    | '/'
    | '/ablauf'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/preise'
    | '/referenzen'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/api/meta-crm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblaufRoute: typeof AblaufRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  PreiseRoute: typeof PreiseRoute
  ReferenzenRoute: typeof ReferenzenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberMichRoute: typeof UeberMichRoute
  ApiMetaCrmRoute: typeof ApiMetaCrmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablauf': {
      id: '/ablauf'
      path: '/ablauf'
      fullPath: '/ablauf'
      preLoaderRoute: typeof AblaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-crm': {
      id: '/api/meta-crm'
      path: '/api/meta-crm'
      fullPath: '/api/meta-crm'
      preLoaderRoute: typeof ApiMetaCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblaufRoute: AblaufRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  PreiseRoute: PreiseRoute,
  ReferenzenRoute: ReferenzenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberMichRoute: UeberMichRoute,
  ApiMetaCrmRoute: ApiMetaCrmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
